spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionnaire_patients
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: clinicease4@gmail.com
    password: sxjm yeay sstn yoee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080